### ISSUE TITLE
Use YKGrid with a ScrollView

### ISSUE THREAD

**Issue by ForceGT** [Unknown-Studios/YourKitchen-iOS#1]
I was looking into your code and now I decided to use the YKGrid view you made using some other open source libraries
I have a use case where I need to use the YKGrid with another Scroll View and both should be scrollable I don't know if this is the right place to ask for help but just pursuing with it

I am attaching an image for reference

![image](https://user-images.githubusercontent.com/31688051/108602386-a6db2d00-73c7-11eb-9fd3-371d0d7297d6.png)

here is my code 
```
VStack{
                    ScrollView(.vertical , showsIndicators: false){
//                        VStack(alignment: .leading, spacing: 10) {
                            BannerView()
                            CategoryRow().environmentObject(self.latestViewModel)
                            ColorRow().environmentObject(self.latestViewModel)
                    }
                            if(latestViewModel.error.isEmpty){
                                YKGrid(latestViewModel.wallpapers,columns: self.columns, vSpacing : 20.0, hSpacing: 5.0,
                                       hPadding: 10.0, endReached: {
                                        //print("End Reached")
                                        self.latestViewModel.getMoreWallpapers()
                                       }){wallpaper in
                                    self.getLatestTabItem(wallpaper: wallpaper)
                                }
                                
}
```

I have just added what I think needs to be changed or what concerns the question and not the other code

**Comment by ForceGT** [comment]
I want both of them to scroll as if it is one scroll view

**Comment by MakakWasTaken** [comment]
I'm a bit unsure what you are trying to achieve. Do you want to make the cards to scroll both vertically and horizontally?

**Comment by ForceGT** [comment]
Here is a screen record
I want to prevent this from happening


https://user-images.githubusercontent.com/31688051/108603142-35ea4400-73cc-11eb-9612-448e748039a2.mov

**Comment by MakakWasTaken** [comment]
I'll look into it and get back to you before or during tomorrow :)

**Comment by ForceGT** [comment]
> I'll look into it and get back to you before or during tomorrow :)

Thank you so much
I can give you the full code if you need ,just let me know if you do

**Comment by MakakWasTaken** [comment]
Have you tried using the header option on the YKGrid class?
Something like the code below.
<img width="313" alt="Screenshot 2021-02-23 at 12 59 35" src="https://user-images.githubusercontent.com/11789635/108840699-08bdb180-75d7-11eb-82ea-63c4acfd9bce.png">

**Comment by ForceGT** [comment]
I haven't tried that though but does that header scroll?
Or I mean you understood what behaviour I wanted right?
Both should be in the same scroll view

**Comment by MakakWasTaken** [comment]
In the solution that I have used, I have made the header scroll with the rest of the content

**Comment by ForceGT** [comment]
That sounds great
I'll try that out and let you know
Not near my PC right now

**Comment by ForceGT** [comment]
Got to the code today and it works as intended 

However I get this error ```Bound preference ScrollOffsetPreferenceKey tried to update multiple times per frame.```

Do you know what could be the reason behind this ?
I think it is associated with the Trackable Scroll View library that you are using but just incase you know a workaround or hack please let me know
Till then my app remains working just in case there is a lot of scroll it crashes

**Comment by ForceGT** [comment]
I would also suggest that you make this custom view that you created out of your brilliance and intelligence a library so that beginners or noobs like me can use it readily

**Comment by MakakWasTaken** [comment]
> I would also suggest that you make this custom view that you created out of your brilliance and intelligence a library so that beginners or noobs like me can use it readily
> 
> 

I'll look into that

**Comment by ForceGT** [comment]
Hey I've dropped you an email from gtxtreme68@icloud.com
I need some more help from you if possible
Can you check?
